### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Shushuda** [Shushuda/Mappy-Continued#1]
Quick TODO, will set this repository up later.

- [ ] Fix options panel.
- [ ] Test everything.
- [ ] Grep for deprecated stuff.
- [ ] Move + - buttons further bottomleft and take them out of BlizzardButtonNames.
- [ ] Make borders for new minimalist buttons to make them more visible
- [ ] Remove deprecated code.

**Comment by Shushuda** [comment]
I'm fixing options now.

I see that textures got kinda changed for blips (minimap node icons). It's broken for all options except default, they don't render the right spot on the blp file. I vaguely remember DF beta having cute separate icons for all different types of nodes. I need to check that out and replace the textures to fix this option.

This is for both large nodes and flashing nodes options.

Also, I've deleted north tag altogether. It's deprecated and removed from the default map, so I won't re-implement it. Maybe I could use it as a replacement for the compass texture, so it rotates when the map rotates.

Also, the map glitches when rotating. It doesn't render anything beside the initial square, so it's just the square that rotates, with empty spots. Not sure how to approach this, especially since I don't even use this feature. I might look into it later, adding to TODO. But it's gonna take a while, I need to research how this works and I already have a lot on my plate with my own addon before DF arrives.

**Comment by Shushuda** [comment]
Detach UI frames seems obsolete at this point.

**Comment by Shushuda** [comment]
Ok, you know what? I'll add a new feature. I want those old rare star symbols on the minimap.

**Comment by Shushuda** [comment]
Ok, my job is done for now. I don't have time to look at minimap rotating, so I will leave it for now.
